# Generated by Django 4.0.4 on 2022-04-29 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300, verbose_name='Categoria')),
                ('name', models.CharField(max_length=300, verbose_name='Transação')),
                ('type', models.CharField(max_length=300, verbose_name='Tipo')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
    ]
